
spring:
  datasource:
    url: jdbc:mysql://111.229.237.107:3306/vote?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
    - classpath:mbgmapper/*.xml

jwt:
   tokenHeader: Authorization #JWT存储的请求头
   secret: vote #JWT加解密使用的密钥
   expiration: 604800 #JWT的超期限时间(60*60*24*7)
   tokenHead: Bearer  #JWT负载中拿到开头
  # log-impl:
  #   org.apache.logging.stdout.StdOutImpl