
spring:
  datasource:
    url: jdbc:mysql://111.229.237.107:3306/vote?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations:
    classpath:mappers/*.xml
  # log-impl:
  #   org.apache.logging.stdout.StdOutImpl

