server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://47.100.210.222:3306/vote?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zc

mybatis:
  mapper-locations:
    classpath:mappers/*.xml
  # log-impl:
  #   org.apache.logging.stdout.StdOutImpl

